//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector
    {
        public Inspector()
        {
            this.User_zayavka = new HashSet<User_zayavka>();
        }
    
        public int ID_Inspecotr { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Otchestvo { get; set; }
        public string DataLiving_street { get; set; }
        public string DataLiving_home { get; set; }
        public string Sex { get; set; }
        public int Phone_number { get; set; }
        public System.DateTime Data_birthday { get; set; }
        public string Email { get; set; }
        public decimal Oklad { get; set; }
    
        public virtual ICollection<User_zayavka> User_zayavka { get; set; }
    }
}
