//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        public int ID_Korzina { get; set; }
        public string Name { get; set; }
        public string Opisanie { get; set; }
        public string Image { get; set; }
        public int ID_Catolog { get; set; }
        public int Sale { get; set; }
        public int Cost { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
