//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_ycher
    {
        public Med_ycher()
        {
            this.User_zayavka = new HashSet<User_zayavka>();
        }
    
        public int ID_Med_ycher { get; set; }
        public string Nazvanie { get; set; }
        public string Street { get; set; }
        public string Number_house { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public string City { get; set; }
        public string License { get; set; }
    
        public virtual ICollection<User_zayavka> User_zayavka { get; set; }
    }
}
