//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nalogi
    {
        public int ID_Nalogi { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Number_house { get; set; }
        public int ID_Otchet { get; set; }
        public int Phone_num { get; set; }
    
        public virtual Otchet Otchet { get; set; }
    }
}
