//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchet
    {
        public Otchet()
        {
            this.Nalogi = new HashSet<Nalogi>();
        }
    
        public int ID_Otchet { get; set; }
        public System.DateTime Date_otchet { get; set; }
        public int ID_Buhgalteria { get; set; }
        public decimal Otchislenie { get; set; }
    
        public virtual Buhgalteria Buhgalteria { get; set; }
        public virtual ICollection<Nalogi> Nalogi { get; set; }
    }
}
