//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_zayavka
    {
        public User_zayavka()
        {
            this.Buhgalteria = new HashSet<Buhgalteria>();
        }
    
        public int ID_Zayavka { get; set; }
        public System.DateTime Date_zayavka { get; set; }
        public int ID_User { get; set; }
        public int ID_Inspector { get; set; }
        public string Prichina { get; set; }
        public decimal Price { get; set; }
        public int ID_Med_ycher { get; set; }
        public Nullable<int> ID_Catolog { get; set; }
    
        public virtual ICollection<Buhgalteria> Buhgalteria { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual Inspector Inspector { get; set; }
        public virtual Med_ycher Med_ycher { get; set; }
        public virtual Users Users { get; set; }
    }
}
